Repository Bugs5382/node-hl7-client, pull requests merged in 2024-06, with the labels that each got.

#95 fix: updated MSH 9.3 builder for Specs 2.4+
  __tests__/hl7.build.test.ts
  __tests__/hl7.sanity.test.ts
  package.json
  pages/builder/index.md
  src/hl7.ts
  src/specification/2.4.ts
  src/specification/2.5.1.ts
  src/specification/2.5.ts
  src/specification/2.6.ts
  src/specification/2.7.1.ts
  src/specification/2.7.ts
  src/specification/2.8.ts
Labels: bug

#97 fix: parsing error
  __tests__/hl7.sanity.test.ts
  src/utils/normalizedBuilder.ts
Labels: bug

#98 feat: merge in fixes
  CHANGELOG.md
  __tests__/hl7.build.test.ts
  __tests__/hl7.sanity.test.ts
  package.json
  pages/builder/index.md
  src/hl7.ts
  src/specification/2.4.ts
  src/specification/2.5.1.ts
  src/specification/2.5.ts
  src/specification/2.6.ts
  src/specification/2.7.1.ts
  src/specification/2.7.ts
  src/specification/2.8.ts
  src/utils/normalizedBuilder.ts
Labels: bug, documentation

#102 fix: connections and threads failing to close
  package.json
  src/client/connection.ts
Labels: bug

#103 chore: update ci
  .github/workflows/ci.yaml
Labels: enhancement

#104 chore: update ci
  .github/workflows/ci.yaml
  .github/workflows/dependabot-action.yml
Labels: enhancement

#105 feat: minor code cleanups
  .github/workflows/deploy-docs.yml
  README.md
  package.json
  src/client/client.ts
  src/client/connection.ts
  src/client/module/inboundResponse.ts
  src/index.ts
  src/utils/normalizedBuilder.ts
  src/utils/utils.ts
  tsconfig.cjs.json
  tsconfig.esm.json
  tsconfig.json
  typedoc.json
Labels: documentation, enhancement

#106 fix: race condition
  .eslintignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/dependabot-action.yml
  .github/workflows/deploy-ci.yaml
  .github/workflows/deploy-docs.yml
  .github/workflows/pr-title-check.yml
  .github/workflows/pr-unit-tests.yml
  package.json
  src/client/connection.ts
  tsconfig.json
  vitest.config.mjs
Labels: bug

#107 feat: update release
  .eslintignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/dependabot-action.yml
  .github/workflows/deploy-ci.yaml
  .github/workflows/deploy-docs.yml
  .github/workflows/pr-title-check.yml
  .github/workflows/pr-unit-tests.yml
  CHANGELOG.md
  README.md
  package.json
  src/client/client.ts
  src/client/connection.ts
  src/client/module/inboundResponse.ts
  src/index.ts
  src/utils/normalizedBuilder.ts
  src/utils/utils.ts
  tsconfig.cjs.json
  tsconfig.esm.json
  tsconfig.json
  tsconfig.types.json
  typedoc.json
  vitest.config.mjs
Labels: bug, documentation, enhancement

#108 chore: docs publish and tsconfig fix
  .github/workflows/deploy-ci.yaml
  .github/workflows/deploy-docs.yml
  README.md
  __tests__/__data__/constants.ts
  __tests__/tsconfig.json
  package.json
  src/tsconfig.build.json
  src/tsconfig.cjs.json
  src/tsconfig.esm.json
  src/tsconfig.json
  src/tsconfig.types.json
  tsconfig.base.json
  typedoc.json
Labels: enhancement

#109 chore: docs and tsconfig fix
  .github/workflows/deploy-ci.yaml
  .github/workflows/deploy-docs.yml
  README.md
  __tests__/__data__/constants.ts
  __tests__/tsconfig.json
  package.json
  src/tsconfig.build.json
  src/tsconfig.cjs.json
  src/tsconfig.esm.json
  src/tsconfig.json
  src/tsconfig.types.json
  tsconfig.base.json
  typedoc.json
Labels: documentation

#112 fix(#100): Ensure correct connection closure
  __tests__/hl7.end2end.test.ts
  src/client/connection.ts
Labels: bug, enhancement

#115 docs: typedoc update
  .github/workflows/deploy-ci.yaml
  .github/workflows/pr-unit-tests.yml
  package.json
  src/builder/batch.ts
  src/builder/fileBatch.ts
  src/builder/message.ts
  src/builder/modules/emptyNode.ts
  src/builder/modules/nodeBase.ts
  src/builder/modules/segment.ts
  src/client/client.ts
  src/client/connection.ts
  src/client/module/inboundResponse.ts
  src/specification/2.1.ts
  src/specification/2.2.ts
  src/specification/2.3.1.ts
  src/specification/2.3.ts
  src/specification/2.4.ts
  src/specification/2.5.1.ts
  src/specification/2.5.ts
  src/specification/2.6.ts
  src/specification/2.7.1.ts
  src/specification/2.7.ts
  src/specification/2.8.ts
  src/specification/specification.ts
  src/utils/enum.ts
  src/utils/normalizedBuilder.ts
  src/utils/normalizedClient.ts
  src/utils/parserPlan.ts
  src/utils/utils.ts
Labels: documentation

#116 docs: update
  .github/workflows/deploy-ci.yaml
  .github/workflows/pr-unit-tests.yml
  package.json
  src/builder/batch.ts
  src/builder/fileBatch.ts
  src/builder/message.ts
  src/builder/modules/emptyNode.ts
  src/builder/modules/nodeBase.ts
  src/builder/modules/segment.ts
  src/client/client.ts
  src/client/connection.ts
  src/client/module/inboundResponse.ts
  src/specification/2.1.ts
  src/specification/2.2.ts
  src/specification/2.3.1.ts
  src/specification/2.3.ts
  src/specification/2.4.ts
  src/specification/2.5.1.ts
  src/specification/2.5.ts
  src/specification/2.6.ts
  src/specification/2.7.1.ts
  src/specification/2.7.ts
  src/specification/2.8.ts
  src/specification/specification.ts
  src/utils/enum.ts
  src/utils/normalizedBuilder.ts
  src/utils/normalizedClient.ts
  src/utils/parserPlan.ts
  src/utils/utils.ts
Labels: documentation

#117 docs: refactoring Message class
  __tests__/hl7.build.test.ts
  pages/builder/index.md
Labels: documentation
